### ISSUE TITLE
Folders?

### ISSUE THREAD

**Issue by TheChymera** [kalsan/fotosort#1]
Nice idea! I've also worked a lot in photo sorting (though I mainly tried to do this automatically into camera-directories with contiguous namespaces on the computer [[1]](https://github.com/TheChymera/repositorg)). But if you are going to introduce operator classification, why constrain yourself to directories? Unlike source-based classification, the relationship between images and figures is many-to-many. For higher-level sorting of images I use tags, and there are nice programs out there (e.g. [tmsu](https://github.com/oniony/TMSU)) which allow you to view tags in your file manager.

**Comment by kalsan** [comment]
Thanks for your input! Appearently GitHub would not send me notifications and the project has been stale for a year, thus the huuuge reply gap. Sorry for that.
Fotosort is destined to be a one-shot sorter for importing photos from an unsorted location. Its solves the specific problem of having many different pictures in a single folder and wanting to distribute them to more sensible directories inside the "photo library". Once pictures are in the library, they are out of scope for Fotosort and other software applies (e.g. Digikam, tools like tmsu etc.).
