### ISSUE TITLE
maybe install into user-local python library folder instead of running sudo pip?

### ISSUE THREAD

**Issue by hellerbarde** [kalsan/fotosort#2]
with `pip install --user .` you can install a python package for the current user only, avoiding cluttering the global /usr/local/ python site-packages folder. The only additional requirement that is then necessary to have the same convenience is that you add `~/.local/bin` to your `$PATH`, which hopefully most people have already done,  because it is so useful. 

cheers, 
Phil

**Comment by kalsan** [comment]
Hi Phil! Thanks for your input and sorry for the huge delay (GH would not send notifications about this project and I haven't worked on it for a year). The user option is mentionned already in the README, is this what you suggest?

**Comment by kalsan** [comment]
Closing as pip was entirely removed from build scripts and the user option is described in README.
